### ISSUE TITLE
VoodooPS2Controller

### ISSUE THREAD

**Issue by 33ddy** [r33int/Hackintosh-Dell-Latitude-E5440#1]
I noticed the performance is a bit lagy in Mojave 10.14.6, I replaced it with [VoodooPS2Controller-Mojave.kext](https://p52.f0.n0.cdn.getcloudapp.com/items/jkuJzZ7K/VoodooPS2Controller-Mojave.kext.zip?v=80cc6a85e54ad9446c75e5894c75bc7d)
compiled from this project in Mojave with the latest Xcode 
[https://github.com/DrHurt/OS-X-ALPS-DRIVER](url)
Now the trackpad act nicely.

**Comment by r33int** [comment]
Hi, thank you for sharing! I am not running hackintosh on my laptop at the moment, but I'll try when I get a chance. Could you file a PR with the modified file? :)

**Comment by wadimw** [comment]
+1 for this kext, version 5.0.0 on 10.14.6 caused Touchpad preference pane to appear empty for me, had some issues with keyboard layout (section sign instead of tilde) and gestures (three finger left right inserted ctrl right left). 33ddy's 6.0.0 was ok (except for 3f drag, but I have adjusted this in touchpad kext plist).

**Comment by r33int** [comment]
Added in 84d44fb :)

**Comment by r33int** [comment]
I tried running this kext on my laptop, and now everything works like a charm. Sensitivity is perfect and the preferences pane is working. Thanks @3ddy for your contribution 😃
